package com.whisnuys.qlinikku.Models;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;

public class Dokter extends PersonDokter implements Serializable {
    private Date lastAutoGeneratedApptDate;
    private List<String> availableAppointmentIDs, prevAppointmentIDs, upcomingAppointmentIDs, seenPatientIDs;

    private Dokter() {
        this.availableAppointmentIDs = new ArrayList<String>();
        this.prevAppointmentIDs = new ArrayList<String>();
        this.upcomingAppointmentIDs = new ArrayList<String>();
        this.seenPatientIDs = new ArrayList<String>();
        this.lastAutoGeneratedApptDate = new Date(0);
    }

    public Dokter(String namaLengkap, String jenisKelamin, String noTelepon,String spesialis, String gambar, String uid){
        super(namaLengkap, jenisKelamin, noTelepon, spesialis,"dokter", gambar, uid);
        this.availableAppointmentIDs = new ArrayList<String>();
        this.prevAppointmentIDs = new ArrayList<String>();
        this.upcomingAppointmentIDs = new ArrayList<String>();
        this.seenPatientIDs = new ArrayList<String>();
        this.availableAppointmentIDs = new ArrayList<String>();
        this.lastAutoGeneratedApptDate = new Date(0);
    }

    public String getNamaLengkap() {
        return namaLengkap;
    }

    public void setNamaLengkap(String namaLengkap) {
        this.namaLengkap = namaLengkap;
    }

    public String getJenisKelamin() {
        return jenisKelamin;
    }

    public void setJenisKelamin(String jenisKelamin) {
        this.jenisKelamin = jenisKelamin;
    }

    public String getNoTelepon() {
        return noTelepon;
    }

    public void setNoTelepon(String noTelepon) {
        this.noTelepon = noTelepon;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getGambar() {
        return gambar;
    }

    public void setGambar(String gambar) {
        this.gambar = gambar;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getSpesialis() {
        return spesialis;
    }

    public void setSpesialis(String spesialis) {
        this.spesialis = spesialis;
    }

    public Date getLastAutoGeneratedApptDate() {
        return lastAutoGeneratedApptDate;
    }

    public List<String> getAvailableAppointmentIDs() {
        return availableAppointmentIDs;
    }

    public void setAvailableAppointmentIDs(List<String> availableAppointmentIDs) {
        this.availableAppointmentIDs = availableAppointmentIDs;
    }

    public List<String> getPrevAppointmentIDs() {
        return prevAppointmentIDs;
    }

    public void setPrevAppointmentIDs(List<String> prevAppointmentIDs) {
        this.prevAppointmentIDs = prevAppointmentIDs;
    }

    public List<String> getUpcomingAppointmentIDs() {
        return upcomingAppointmentIDs;
    }

    public void setUpcomingAppointmentIDs(List<String> upcomingAppointmentIDs) {
        this.upcomingAppointmentIDs = upcomingAppointmentIDs;
    }

    public List<String> getSeenPatientIDs() {
        return seenPatientIDs;
    }

    public void setSeenPatientIDs(List<String> seenPatientIDs) {
        this.seenPatientIDs = seenPatientIDs;
    }

    public void setLastAutoGeneratedApptDate(Date lastAutoGeneratedApptDate) {
        this.lastAutoGeneratedApptDate = lastAutoGeneratedApptDate;
    }

    public void addAvailableAppointment(Appointment availableAppt) {
        this.availableAppointmentIDs.add(availableAppt.getAppointmentID());
    }

    public void removeAvailableAppointment(String availableApptID) {
        this.availableAppointmentIDs.remove(availableApptID);
    }

    public void removeAvailableAppointment(Appointment availableAppt) {
        this.removeAvailableAppointment(availableAppt.getAppointmentID());
    }
}
